// Auto-generated by MicaNT codegen from win32metadata (MIT License)
// Standard: ISO C++23
#pragma once

#include <string_view>
#include <array>
#include <cstdint>

namespace micant::generated {

struct ApiDefinition {
    std::string_view name;
    std::string_view header;
    std::string_view category;
};

inline constexpr std::array<ApiDefinition, 16> NtSystemCallCatalog = {{
    { "NtQueryInformationProcess", "winternl.h", "backup" },
    { "NtQueryInformationThread", "winternl.h", "backup" },
    { "NtmsObjectsTypes", "ntmsapi.h", "fs" },
    { "NtCurrentTeb", "winnt.h", "Kernel" },
    { "NtClose", "winternl.h", "winprog" },
    { "NtCreateFile", "winternl.h", "winprog" },
    { "NtDeviceIoControlFile", "winternl.h", "winprog" },
    { "NtNotifyChangeMultipleKeys", "winternl.h", "winprog" },
    { "NtOpenFile", "winternl.h", "winprog" },
    { "NtQueryMultipleValueKey", "winternl.h", "winprog" },
    { "NtQueryObject", "winternl.h", "winprog" },
    { "NtQuerySystemInformation", "winternl.h", "winprog" },
    { "NtQuerySystemTime", "winternl.h", "winprog" },
    { "NtRenameKey", "winternl.h", "winprog" },
    { "NtSetInformationKey", "winternl.h", "winprog" },
    { "NtWaitForSingleObject", "winternl.h", "winprog" },
}};

inline constexpr std::array<ApiDefinition, 57> RtlRoutineCatalog = {{
    { "RtlFirstEntrySList", "winnt.h", "backup" },
    { "RtlInitializeSListHead", "winnt.h", "backup" },
    { "RtlInterlockedFlushSList", "winnt.h", "backup" },
    { "RtlInterlockedPopEntrySList", "winnt.h", "backup" },
    { "RtlInterlockedPushEntrySList", "winnt.h", "backup" },
    { "RtlQueryDepthSList", "winnt.h", "backup" },
    { "RtlAddFunctionTable", "winnt.h", "Debug" },
    { "RtlAddGrowableFunctionTable", "winnt.h", "Debug" },
    { "RtlCaptureContext", "winnt.h", "Debug" },
    { "RtlDeleteFunctionTable", "winnt.h", "Debug" },
    { "RtlDeleteGrowableFunctionTable", "winnt.h", "Debug" },
    { "RtlGrowFunctionTable", "winnt.h", "Debug" },
    { "RtlInstallFunctionTableCallback", "winnt.h", "Debug" },
    { "RtlLookupFunctionEntry", "winnt.h", "Debug" },
    { "RtlPcToFileHeader", "winnt.h", "Debug" },
    { "RtlRestoreContext", "winnt.h", "Debug" },
    { "RtlUnwind", "winnt.h", "Debug" },
    { "RtlUnwind2", "winnt.h", "Debug" },
    { "RtlUnwindEx", "winnt.h", "Debug" },
    { "RtlVirtualUnwind", "winnt.h", "Debug" },
    { "RtlNtStatusToDosError", "winternl.h", "Debug" },
    { "RtlCaptureStackBackTrace", "winnt.h", "ifsk" },
    { "RtlEthernetAddressToStringA", "ip2string.h", "IpHlp" },
    { "RtlEthernetAddressToStringW", "ip2string.h", "IpHlp" },
    { "RtlEthernetStringToAddressA", "ip2string.h", "IpHlp" },
    { "RtlEthernetStringToAddressW", "ip2string.h", "IpHlp" },
    { "RtlIpv4AddressToStringA", "ip2string.h", "IpHlp" },
    { "RtlIpv4AddressToStringExW", "ip2string.h", "IpHlp" },
    { "RtlIpv4AddressToStringW", "ip2string.h", "IpHlp" },
    { "RtlIpv4StringToAddressA", "ip2string.h", "IpHlp" },
    { "RtlIpv4StringToAddressExW", "ip2string.h", "IpHlp" },
    { "RtlIpv4StringToAddressW", "ip2string.h", "IpHlp" },
    { "RtlIpv6AddressToStringA", "ip2string.h", "IpHlp" },
    { "RtlIpv6AddressToStringExW", "ip2string.h", "IpHlp" },
    { "RtlIpv6AddressToStringW", "ip2string.h", "IpHlp" },
    { "RtlIpv6StringToAddressA", "ip2string.h", "IpHlp" },
    { "RtlIpv6StringToAddressExW", "ip2string.h", "IpHlp" },
    { "RtlIpv6StringToAddressW", "ip2string.h", "IpHlp" },
    { "RtlDecryptMemory", "ntsecapi.h", "security" },
    { "RtlEncryptMemory", "ntsecapi.h", "security" },
    { "RtlGenRandom", "ntsecapi.h", "security" },
    { "RtlConvertSidToUnicodeString", "winternl.h", "security" },
    { "RtlRaiseException", "rtlsupportapi.h", "winprog" },
    { "RtlAnsiStringToUnicodeString", "winternl.h", "winprog" },
    { "RtlCharToInteger", "winternl.h", "winprog" },
    { "RtlFreeAnsiString", "winternl.h", "winprog" },
    { "RtlFreeOemString", "winternl.h", "winprog" },
    { "RtlFreeUnicodeString", "winternl.h", "winprog" },
    { "RtlInitString", "winternl.h", "winprog" },
    { "RtlInitUnicodeString", "winternl.h", "winprog" },
    { "RtlIsNameLegalDOS8Dot3", "winternl.h", "winprog" },
    { "RtlLocalTimeToSystemTime", "winternl.h", "winprog" },
    { "RtlTimeToSecondsSince1970", "winternl.h", "winprog" },
    { "RtlUnicodeStringToAnsiString", "winternl.h", "winprog" },
    { "RtlUnicodeStringToOemString", "winternl.h", "winprog" },
    { "RtlUnicodeToMultiByteSize", "winternl.h", "winprog" },
    { "RtlUniform", "winternl.h", "winprog" },
}};

} // namespace micant::generated
